#!/usr/bin/env bash
# Install nginx and configure a custom HTTP response header

apt-get update -y
apt-get install nginx -y

HOSTNAME=$(hostname)

sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-available/default

systemctl restart nginx
