#!/usr/bin/env bash
# Configure Nginx with a custom HTTP response header
# shellcheck disable=SC2154

# Install nginx
apt-get update -y
apt-get install nginx -y

# Get hostname
HOSTNAME=$(hostname)

# Add custom header to nginx default site
sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart nginx
systemctl restart nginx
