#!/usr/bin/env bash
# Install and configure HAProxy load balancer

apt-get -y update
apt-get -y install haproxy

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Remove previous frontend/backend config if script runs again
sed -i '/frontend http_front/,$d' /etc/haproxy/haproxy.cfg

printf "\nfrontend http_front\n\tbind *:80\n\tdefault_backend web_back\n\nbackend web_back\n\tbalance roundrobin\n\tserver web-01 172.212.192.18:80 check\n\tserver web-02 172.90.174.46:80 check\n" >> /etc/haproxy/haproxy.cfg

service haproxy restart
