#!/usr/bin/env bash
# Install and configure HAProxy

apt-get update -y
apt-get install -y haproxy

# Enable HAProxy service
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
cat <<EOF >> /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 18.212.192.18:80 check
    server web-02 52.90.174.46:80 check
EOF

service haproxy restart
